# -*- coding: utf-8 -*-
"""用户可见指标的统一解释目录。

这里保存页面浮层与透明度说明页共用的文案。公式必须与运行代码保持一致，
避免同一个指标在不同页面出现不同解释。
"""


METRIC_EXPLANATION_GROUPS = [
    {
        'id': 'heat-action',
        'title': '今日热风险与行动',
        'description': '公开风险页、首页和老人模式共用的即时热风险规则。',
        'keys': [
            'heat_risk_score',
            'heat_index',
            'personal_threshold',
            'action_confirmation_rate',
            'action_escalation_rate',
            'action_help_rate',
        ],
    },
    {
        'id': 'forecast',
        'title': '7 天预测',
        'description': '地区级复合暴露评分、门诊高负荷概率和可预报性。',
        'keys': ['forecast_exposure_score', 'forecast_visit_probability', 'forecast_predictability'],
    },
    {
        'id': 'personal',
        'title': '个人健康与慢病评估',
        'description': '个人风险融合、即时筛查、慢病相对风险和决策矩阵。',
        'keys': [
            'member_risk_score',
            'profile_completion',
            'personal_health_score',
            'screening_score',
            'chronic_risk_score',
            'personal_impact_likelihood',
        ],
    },
    {
        'id': 'ml',
        'title': '机器学习分类',
        'description': 'RandomForest 疾病类别输出及特征重要性，供风险线索参考。',
        'keys': ['ml_class_probability', 'ml_feature_importance'],
    },
    {
        'id': 'community',
        'title': '社区风险地图',
        'description': '天气危险度、社区脆弱性、历史病例负担、不确定性与空间热点。',
        'keys': [
            'community_weather_hazard',
            'community_risk_index',
            'community_impact_likelihood',
            'community_weather_rr',
            'community_vi',
            'community_svi',
            'sir',
            'smoothed_sir',
            'rr_probability',
            'uncertainty_index',
            'gistar',
            'expected_excess',
            'data_coverage',
        ],
    },
    {
        'id': 'gis',
        'title': '1 km 热暴露 GIS',
        'description': '都昌县原生 MODIS 网格中的晴空地表温度、年龄结构人口、地表覆盖和表面高程。',
        'keys': [
            'gis_native_grid',
            'gis_age65_share',
            'gis_lst_mean',
            'gis_q3_coverage',
            'gis_tree_cover',
            'gis_built_up',
            'gis_permanent_water',
            'gis_mean_elevation',
            'gis_validation',
        ],
    },
    {
        'id': 'validation',
        'title': '模型可靠性',
        'description': '回测误差与区间覆盖指标。',
        'keys': ['mae', 'rmse', 'interval_coverage'],
    },
]


METRIC_EXPLANATIONS = {
    'heat_risk_score': {
        'anchor': 'heat-risk-score',
        'title': '热风险综合评分（0–100）',
        'summary': '衡量今天需要多积极采取防暑行动。它是行动优先级，不是疾病发生概率。',
        'formula': 'Score = 100 × [0.50×HI_norm + 0.30×Night_norm + 0.20×Streak_norm]',
        'variables': [
            'HI_norm = clip((体感热−30)/12, 0, 1)',
            'Night_norm = clip((夜间最低温−24)/6, 0, 1)',
            'Streak_norm = clip((连续高温天数−1)/4, 0, 1)',
        ],
        'thresholds': ['低风险 <35', '中风险 35–54.9', '高风险 55–74.9', '极高风险 ≥75'],
        'method': 'HeatActionService 线性加权规则',
        'window': '当前温度/湿度、当日夜间最低温、截至当天的连续高温天数',
        'missing': '公开风险与行动页仅接受来源明确的真实天气；气温、最高温、最低温或湿度任一缺失时停止计算并显示“等待真实天气”。连续天数缺失时按 0 天。',
        'limitations': ['用于通用行动提醒', '不包含个人病史', '缺失历史天气时可能低估连续高温风险'],
        'source_file': 'services/heat_action_service.py',
    },
    'heat_index': {
        'anchor': 'heat-index',
        'title': '体感热（Heat Index）',
        'summary': '把气温和相对湿度合成一个体感温度。湿度越高，同一气温下通常越闷热。',
        'formula': 'HI = −8.784695 + 1.61139411T + 2.338549R − 0.14611605TR − 0.012308094T² − 0.016424828R² + 0.002211732T²R + 0.00072546TR² − 0.000003582T²R²',
        'variables': ['T = 摄氏气温', 'R = 相对湿度百分数'],
        'thresholds': ['30°C 以下在热风险分项中记 0', '42°C 及以上在热风险分项中记满分'],
        'method': '气温与湿度经验公式',
        'window': '当前天气观测',
        'missing': '公开风险与行动页在湿度缺失时停止风险计算；底层公式单独调用时会退回当前气温。',
        'limitations': ['未单独加入风、太阳辐射、衣着或活动强度'],
        'source_file': 'services/heat_action_service.py',
    },
    'personal_threshold': {
        'anchor': 'personal-threshold',
        'title': '个人阈值拨片',
        'summary': '只改变页面如何把同一个分数分级，不改变服务器计算出的原始分数。',
        'formula': '分级阈值 = 0.35/0.55/0.75 + 调整值（−0.1、0、+0.1）',
        'variables': ['−0.1 = 更早提醒', '0 = 默认', '+0.1 = 更晚升级'],
        'thresholds': ['阈值会进行边界保护，保持四级顺序'],
        'method': '浏览器本地分级规则',
        'window': '持续保存在当前浏览器',
        'missing': '没有保存值时使用 0。',
        'limitations': ['不会上传服务器', '不会改变模型或其他用户看到的结果'],
        'source_file': 'templates/risk.html',
    },
    'action_confirmation_rate': {
        'anchor': 'action-confirmation-rate',
        'title': '行动确认覆盖率',
        'summary': '当天已完成安全确认的有效监测对象，占该社区全部有效监测对象的比例。',
        'formula': 'ConfirmRate = ConfirmedToday / ActivePairsInCommunity',
        'variables': ['ConfirmedToday = 当天 confirmed_at 已填写且绑定仍为 active 的对象数', 'ActivePairsInCommunity = 状态为 active 的绑定数'],
        'thresholds': ['只描述行动覆盖，不代表健康改善'],
        'method': '行动状态计数',
        'window': '本地日期当天',
        'missing': '有效监测对象为 0 时不可计算，页面显示 --。',
        'limitations': ['未确认可能代表尚未操作，不等于不安全'],
        'source_file': 'services/user/_helpers.py',
    },
    'action_escalation_rate': {
        'anchor': 'action-escalation-rate',
        'title': '升级触发率',
        'summary': '当天已进入 backup 或更高升级阶段的对象，占社区有效监测对象的比例。',
        'formula': 'EscalationRate = EscalatedToday / ActivePairsInCommunity',
        'variables': ['EscalatedToday = 当天 relay_stage 顺序达到 backup 及以上且绑定仍为 active 的对象数'],
        'thresholds': ['数值升高表示需要更多人工跟进'],
        'method': '行动升级链计数',
        'window': '本地日期当天',
        'missing': '有效监测对象为 0 时不可计算，页面显示 --。',
        'limitations': ['受人工点击、超时规则和流程执行完整度影响'],
        'source_file': 'services/user/_helpers.py',
    },
    'action_help_rate': {
        'anchor': 'action-help-rate',
        'title': '求助率',
        'summary': '当天 help_flag 为真的对象，占社区有效监测对象的比例。',
        'formula': 'HelpRate = HelpFlagToday / ActivePairsInCommunity',
        'variables': ['同一 active 绑定对象当天按一条状态记录计数', 'inactive 绑定的历史状态不进入分子或分母'],
        'thresholds': ['用于安排回访优先级，没有医学严重程度含义'],
        'method': '行动求助标记计数',
        'window': '本地日期当天',
        'missing': '有效监测对象为 0 时不可计算，页面显示 --。',
        'limitations': ['未点击求助不能证明没有困难'],
        'source_file': 'services/user/_helpers.py',
    },
    'forecast_exposure_score': {
        'anchor': 'forecast-exposure',
        'title': '7 天复合暴露评分（0–100）',
        'summary': '地区级天气与环境暴露分数。当前计算不使用家庭成员的慢病资料。',
        'formula': 'Score = clip(0.34×Heat + 0.28×PM2.5 + 0.18×Humidity + 0.20×HotNight + SynergyBonus, 0, 100)',
        'variables': [
            'Heat = clip((校正平均温度−28)×6, 0, 100)',
            'PM2.5 = clip((PM2.5−35)×1.8, 0, 100)',
            'Humidity = clip((相对湿度−70)×2.4, 0, 100)',
            'HotNight = 夜间最低温分档为 8/45/72/100',
            '协同加分：热+污染加8，热+高湿加6，热夜+污染加4，可叠加到18',
        ],
        'thresholds': ['低 <45', '中 45–69.9', '高 ≥70'],
        'method': 'ForecastService 复合暴露规则',
        'window': '未来 7 天逐日预报',
        'missing': '生产页面要求 7 天逐日最高温、最低温、平均温和湿度均为有限数，任一缺失时整页显示预报不可用。PM2.5 优先级：未来日直接值 → 当前实况 PM2.5 复用 → 未来日 AQI×0.65 → 当前实况 AQI×0.65 → 默认 AQI 50×0.65；浮层逐日标记真实来源。底层独立调用仍保留湿度60%与最低温回退，并明确标为插补。',
        'limitations': ['地区级筛查分数', '不等于个人疾病概率', '当前实况复用不代表未来日空气质量预报', 'AQI 转 PM2.5 与默认 AQI 50 均为代理值'],
        'source_file': 'services/forecast_service.py',
    },
    'forecast_visit_probability': {
        'anchor': 'forecast-visits',
        'title': '门诊高负荷概率',
        'summary': '预测日门诊量超过历史 P90 阈值的概率。',
        'formula': 'RawVisits = SeasonalBaseline × RR × WeekdayFactor；SD = sqrt(RawVisits + RawVisits²/2)；P(high) ≈ 1 − Φ((P90−RawVisits)/SD)',
        'variables': ['RR = 温度与滞后温度相对风险', '周末因子 0.7，周一因子 1.1，其余 1.0', '概率使用限幅前 RawVisits；页面门诊量随后最多限到历史峰值×2'],
        'thresholds': ['正常 ≤15%', '黄色提醒 >15%', '橙色预警 >30%', '红色预警 >50%'],
        'method': 'DLNM RR + 季节基线 + 正态近似',
        'window': '未来 7 天；温度滞后最多 7 天',
        'missing': '历史阈值不可用时概率退回 10%。',
        'limitations': ['属于试点预测', '概率校准仍需时间切分回测', '不能替代医疗资源排班判断'],
        'source_file': 'services/forecast_service.py',
    },
    'forecast_predictability': {
        'anchor': 'forecast-predictability',
        'title': '可预报性评分',
        'summary': '表示多模型分歧、提前天数和模型数量对天气预报可信度的影响。',
        'formula': '外部分支：clip(ExternalScore,0,100)；本地分支：clip(100−16×模型温差−3×(提前天数−1)+min(8,2×(模型数−1)),5,99)',
        'variables': ['只要上游提供 ExternalScore 就直接使用外部分支', '本地分支中模型温差与提前天数降低分数，多模型最多加 8 分'],
        'thresholds': ['低 <50', '中 50–74.9', '高 ≥75'],
        'method': '预报分歧启发式评分',
        'window': '每个预报日单独计算',
        'missing': '没有外部分数时走本地分支；模型温差缺失按 0，模型数最少按 1。浮层会标记本日分支。',
        'limitations': ['衡量天气输入稳定性，不代表健康模型准确率'],
        'source_file': 'services/forecast_service.py',
    },
    'member_risk_score': {
        'anchor': 'member-risk-score',
        'title': '家庭成员档案风险（0–100）',
        'summary': '根据档案中的年龄、慢病、风险标签、自测指标和天气敏感阈值进行规则加分。',
        'formula': 'Score = clip(15 + AgePoints + DiseasePoints + TagPoints + MetricPoints + SensitivityPoints, 0, 100)',
        'variables': [
            '年龄加 0/10/20/25/30 分',
            '慢病每项加 8 分，最多 30 分',
            '风险标签每项加 5 分，最多 20 分',
            '血压偏高加 10，血糖偏高加 10，心率偏快加 8',
            '高温/低温敏感阈值各可加 6 分',
        ],
        'thresholds': ['低风险 <40', '中风险 40–69', '高风险 ≥70'],
        'method': '家庭成员档案加分规则',
        'window': '当前保存的成员档案',
        'missing': '未填写字段不加分。',
        'limitations': ['没有使用当天实时天气数值', '只用于家庭照护排序', '不提供医学诊断'],
        'source_file': 'core/health_profiles.py',
    },
    'profile_completion': {
        'anchor': 'profile-completion',
        'title': '档案完善度',
        'summary': '已填写的档案项目占当前参与检查项目的比例。',
        'formula': 'Completion = FilledFields / TotalCheckedFields × 100%',
        'variables': ['基础档案检查关系、年龄、性别、慢病', '有扩展档案时再检查过敏、药物、指标、风险标签、天气阈值和联系人'],
        'thresholds': ['百分比只表示字段是否存在，不评价内容质量'],
        'method': '字段完整性计数',
        'window': '当前保存的成员档案',
        'missing': '没有扩展档案时只以 4 个基础字段为分母。',
        'limitations': ['不同成员的分母可能为 4 或 10', '不能代表健康数据准确性'],
        'source_file': 'core/health_profiles.py',
    },
    'personal_health_score': {
        'anchor': 'personal-health-score',
        'title': '个人健康风险得分（0–100）',
        'summary': '融合温度相对风险、空气质量、即时筛查、个人易感性、社区背景和慢病规则。',
        'formula': 'Final = 0.85×(0.45×PathA + 0.30×PathB + 0.25×PathC) + 0.15×Chronic',
        'variables': [
            'TempScore = clip((温度RR−1)/1.2×100, 0, 100)',
            'PathA = 50%温度分 + 28%个人易感性 + 22%AQI',
            'PathB = 30%极端天气 + 30%AQI + 15%湿度 + 25%即时筛查',
            'CommunityBackground = 65%社区VI + 35%社区30日负担分',
            'PathC = 40%社区背景 + 35%个人易感性 + 25%温度分',
        ],
        'thresholds': ['低风险 <40', '中风险 40–69.9', '高风险 ≥70'],
        'method': 'HealthRiskService 三路径融合',
        'window': '当前天气、温度滞后、30 天社区病例、当天 5 项筛查',
        'missing': '实时天气为模拟、来源不明或缺少气温时停止评估且不保存结果。社区 VI 缺失时使用 45 分代理；人口缺失导致30日每千人负担不可计算时使用 30 分代理，页面逐项标记。缺少筛查项时使用各题默认档。',
        'limitations': ['属于行动筛查', '权重为可审计规则', '社区代理值会在结果页明确标记', '不提供诊断或处方'],
        'source_file': 'services/health_risk_service.py',
    },
    'screening_score': {
        'anchor': 'screening-score',
        'title': '即时筛查分数',
        'summary': '把 5 个当日自报项目转换成一个 0–100 的规则分数。',
        'formula': 'Screen = 0.30×症状 + 0.25×户外暴露 + 0.15×饮水 + 0.20×服药 + 0.10×睡眠',
        'variables': ['每个答案先映射为固定档位分数，再按权重相加'],
        'thresholds': ['该分数只作为个人融合模型中的一个分项'],
        'method': '五项问卷线性加权',
        'window': '用户本次提交',
        'missing': '未识别答案会退回该题默认档。',
        'limitations': ['自报信息可能有偏差', '严重症状应直接寻求专业帮助'],
        'source_file': 'services/health_risk_service.py',
    },
    'chronic_risk_score': {
        'anchor': 'chronic-risk-score',
        'title': '慢病风险得分（0–100）',
        'summary': '公开 DLNM 内层病种/年龄修正、慢病层年龄/共病修正，以及已提交血压/血糖对分数的影响。',
        'formula': 'DLNMAdjustedRR = min(RawDLNMRR×DLNMDiseaseModifier×DLNMAgeModifier, RRcap)；PersonalRR = DLNMAdjustedRR×ChronicAgeAmplifier×ComorbidityAmplifier；DiseaseScore = min(100, 30×PersonalRR + VitalAdjustment×Relevance)',
        'variables': ['DLNMAgeModifier 来自 DLNM 文献先验年龄层', 'ChronicAgeAmplifier 是慢病服务的第二层病种年龄规则', '总体得分取各相关病种得分的最大值', 'Relevance：general/心血管=1.0，其他病种=0.4', '血压/血糖原始修正最多 18 分'],
        'thresholds': ['低风险 <40', '中风险 40–69.9', '高风险 ≥70'],
        'method': 'DLNM RR + 年龄/共病/生命体征规则',
        'window': '当前天气与近 7 天自测指标',
        'missing': '模拟天气、来源不明或气温缺失时页面停止评估；未填写血压或血糖时不加生命体征修正。',
        'limitations': ['两层年龄修正会叠乘，页面逐层显示，仍需用真实样本校准', '用药依从和自由文本症状当前只作补充观察，不进入总分', '不用于调整药物'],
        'source_file': 'services/chronic_risk_service.py',
    },
    'personal_impact_likelihood': {
        'anchor': 'personal-impact-likelihood',
        'title': '个人 Impact × Likelihood 矩阵',
        'summary': '把个人健康影响强度与模型高风险可能性分档，用于安排照护响应优先级。',
        'formula': 'Impact = 0.70×FinalRisk + 0.30×Screening；Likelihood = clip(100×P(high) + CertaintyAdjustment, 0, 100)；Matrix = ImpactRank×LikelihoodRank',
        'variables': ['确定性 likely 加 8，unlikely 减 8，possible 不调整', '两轴均按 0–24.9/25–49.9/50–74.9/75–100 分成 1–4 档'],
        'thresholds': ['矩阵得分为 1–16，越高越需要优先核查和行动'],
        'method': '个人四档行动分流矩阵',
        'window': '跟随本次个人健康评估',
        'missing': '历史记录缺少新拆解字段时显示不可回算。',
        'limitations': ['用于行动分流', '不表示精确发病概率'],
        'source_file': 'services/health_risk_service.py',
    },
    'community_impact_likelihood': {
        'anchor': 'community-impact-likelihood',
        'title': '社区 Impact × Likelihood 矩阵',
        'summary': '把社区影响强度与门诊记录 O/E 高于 1 的可能性分档，用于人工分流和资源排序。',
        'formula': 'Impact = min(100, 0.75×RiskIndex + 6×ExpectedExcess)；Likelihood = clip(100×P(O/E>1) + CertaintyAdjustment, 0, 100)；Matrix = ImpactRank×LikelihoodRank',
        'variables': ['确定性 high 加 10，low 减 10，medium 不调整', '两轴均按 0–34.9/35–54.9/55–74.9/75–100 分成 1–4 档'],
        'thresholds': ['矩阵得分为 1–16；无匹配病例时 Likelihood 不可计算'],
        'method': '社区四档人工分流矩阵',
        'window': '当天综合风险与所选病例窗口',
        'missing': '没有匹配病例时历史可能性与矩阵结果标记为数据不足。',
        'limitations': ['用于人工核查和行动排序', '不表示自动医疗决策'],
        'source_file': 'services/community_risk_service.py',
    },
    'ml_class_probability': {
        'anchor': 'ml-attention-score',
        'title': '天气调整疾病类别关注分（0–100）',
        'summary': 'RandomForest 原始类别概率经天气敏感规则放大后的关注分。各类别没有再次归一化，合计可能超过 100。',
        'formula': 'AttentionScore = 100 × min(RFClassProbability × AppliedWeatherMultiplier, 0.95)',
        'variables': ['输入含年龄、性别、时间和天气特征', '页面同时展示原始 RF 概率、实际天气倍率和最终关注分', '极端温湿度可按病种敏感度放大'],
        'thresholds': ['只用于类别线索排序，没有临床风险分级'],
        'method': 'RandomForest 多分类模型 + 天气规则修正',
        'window': '当前输入快照',
        'missing': '模拟天气、来源不明或气温缺失时页面停止推理。真实天气的最低/最高温缺失时按平均温度±5°C；体感温度缺失时由温湿度现场计算，其余训练特征按模型默认值补齐。',
        'limitations': ['训练准确率约 65.3%，F1 约 64.2%', '天气调整后没有概率归一化', '未证明为个体发病概率', '不能用于诊断'],
        'source_file': 'services/ml_prediction_service.py / models/feature_config.json',
    },
    'ml_feature_importance': {
        'anchor': 'ml-feature-importance',
        'title': '模型特征重要性',
        'summary': '表示某个特征在整棵随机森林中平均贡献了多少分裂信息。',
        'formula': 'Importance = 该特征带来的归一化不纯度下降总和',
        'variables': ['所有特征重要性之和约为 1'],
        'thresholds': ['数值用于全局排序，没有个人正负因果含义'],
        'method': 'RandomForest impurity-based feature importance',
        'window': '模型训练数据整体',
        'missing': '模型元数据缺失时不展示示例数值。',
        'limitations': ['不能说明因果', '相关特征可能分摊重要性', '不等于本次个人贡献'],
        'source_file': 'models/feature_config.json',
    },
    'community_weather_hazard': {
        'anchor': 'community-weather-hazard',
        'title': '社区天气危险度 Hazard（0–100）',
        'summary': '把当前天气相对风险、社区脆弱性和日基线门诊量合成可比较的天气危险度。',
        'formula': 'Excess = max(WeatherRR−1, 0)×VI×BaselineVisits；Hazard = clip((1−exp(−Excess/Efold))×100, 0, 100)',
        'variables': [
            'WeatherRR = 当前及滞后温度相对风险',
            'VI = 社区脆弱性倍数',
            'BaselineVisits = clip(社区人口×0.03, 1, 20)',
            'Efold = 指数映射尺度，默认 10，可由配置调整',
        ],
        'thresholds': ['Hazard 越高表示天气驱动的社区行动优先级越高', '最终项目综合风险仍会再加入 SVI 与历史负担'],
        'method': '超额门诊估计 + 指数饱和映射',
        'window': '当天及在线 RR 实际使用的滞后温度窗口',
        'missing': '天气相对风险不高于 1 时 Excess 为 0；天气数据不可用时整条社区风险链停止计算。',
        'limitations': ['BaselineVisits 是人口规则估计', 'Efold 为项目配置参数', 'Hazard 不等于发病概率'],
        'source_file': 'services/community_risk_service.py',
    },
    'community_risk_index': {
        'anchor': 'community-risk-index',
        'title': '社区综合风险指数（0–100）',
        'summary': '将天气危险度、SVI-like 脆弱性和历史病例负担合成社区行动排序分数。',
        'formula': '有历史：Risk=(0.45×Hazard+0.35×SVI+0.20×Burden)×Penalty；无历史：Risk=0.5625×Hazard+0.4375×SVI',
        'variables': ['Hazard = 天气超额风险的 0–100 映射', 'SVI = 多主题脆弱性分位', 'Burden = 平滑 O/E 的社区分位', '有历史且不确定性≥70时 Penalty=0.93，否则为1'],
        'thresholds': ['项目综合风险等级：0=0–19，1=20–39，2=40–59，3=60–79，4=80–100'],
        'method': '社区多维线性综合指数',
        'window': '当天气象 + 选定历史病例窗口（默认 30 天）',
        'missing': 'Community 表为空或查询失败时不生成地图与排名。没有匹配门诊记录时历史分量为 null，并将天气与 SVI 权重重新归一；单个社区结构字段缺失时使用稳定中性代理。',
        'limitations': ['用于社区排序', '代理字段仍需真实调查数据替换', '不用于比较个人'],
        'source_file': 'services/community_risk_service.py',
    },
    'community_weather_rr': {
        'anchor': 'community-weather-rr',
        'title': '天气相对风险（RR）',
        'summary': '表示当前及滞后温度下，相对参考温度的门诊风险倍数。RR=1 表示基线。',
        'formula': '训练分支：FinalRR = min(BaseRR × DiseaseModifier × AgeModifier, CumulativeCap)；未训练分支：RR = 1 + 0.015×|T−20|',
        'variables': ['BaseRR 来自已导出的温度–RR 曲线，在线按温度插值，并可叠加滞后温度权重', '当前 production profile 的单日 cap=2.6；profile 未加载时文献先验单日 cap=2.2；累计 cap=3.5', '未训练分支直接返回简化 RR，不叠加病种/年龄修正'],
        'thresholds': ['RR >1 表示高于参考水平', '训练分支会在返回明细中标记实际 cap 与是否触发'],
        'method': '离线 quasi-Poisson GLM + DLNM 曲线；在线读取 RR profile',
        'window': '当前在线计算实际使用滞后 0–7 天；配置中的冷效应 14 天尚未进入当前循环',
        'missing': 'profile 不可用时退回本地数据/文献先验及 2.2 单日 cap；模型未训练时使用简化偏离公式并返回提示。',
        'limitations': ['当前 production profile 仍有残差自相关', 'RR 曲线需要继续做时间切分验证'],
        'source_file': 'analysis/duchang_health_weather/scripts/fit_dlnm.R / services/dlnm_risk_service.py',
    },
    'community_vi': {
        'anchor': 'community-vi',
        'title': '社区脆弱性指数（VI）',
        'summary': '按老龄、慢病、绿地、热岛和医疗可达性计算的可审计线性指数。',
        'formula': 'VI = max(0.5, 1 + 1.5×老龄率 + 1.8×慢病率 − 0.8×绿地率 + 0.5×热岛指数 − 0.3×医疗可达性)',
        'variables': ['比例均应使用 0–1 单位', '负权重代表保护因素'],
        'thresholds': ['低 <1.2', '中 1.2–1.49', '高 ≥1.5'],
        'method': '社区线性脆弱性规则',
        'window': '社区档案当前版本',
        'missing': '缺失结构字段使用稳定的中性代理值，不再随机生成。',
        'limitations': ['代理字段不等于实测 GIS 或医疗可达性', '现有社区原始脆弱性字段存在单位不一致警告'],
        'source_file': 'services/community_risk_service.py',
    },
    'community_svi': {
        'anchor': 'community-svi',
        'title': 'SVI-like 脆弱性分位（0–100）',
        'summary': '表示某社区相对当前社区集合的脆弱程度，100 代表相对最脆弱。',
        'formula': 'SVI = 0.40×SensitivityPct + 0.25×ExposurePct + 0.35×AdaptiveGapPct',
        'variables': ['Sensitivity = 0.6×老龄率 + 0.4×慢病率', 'Exposure = 热岛指数', 'AdaptiveGap = 0.5×(1−绿地率) + 0.5×(1−医疗可达性)'],
        'thresholds': ['Q1 <25', 'Q2 25–49.9', 'Q3 50–74.9', 'Q4 ≥75'],
        'method': '当前社区集合内的三主题分位指数',
        'window': '本次参与分析的社区集合',
        'missing': '主题字段缺失时使用稳定代理值。',
        'limitations': ['SVI-like 为项目内部指标', '不能直接等同 CDC SVI', '社区集合变化会改变分位'],
        'source_file': 'services/community_risk_service.py',
    },
    'sir': {
        'anchor': 'sir',
        'title': '门诊记录观察/期望比（O/E，兼容字段 SIR）及 95% CI',
        'summary': '比较某社区窗口内的门诊记录条数与按全体粗率、人口和分析天数推算的期望记录数。',
        'formula': 'O/E = ObservedVisitRecords / ExpectedVisitRecords；Expected = 全体匹配记录粗率×社区人口×窗口天数',
        'variables': ['Observed 是 MedicalRecord 行数，不能保证每行代表一位新发患者', '观察数>0时 CI≈exp(log(O/E)±1.96/√Observed)；观察数=0时上界=3/Expected'],
        'thresholds': ['O/E=1 为当前粗率基线', 'O/E>1 表示记录数高于期望', '区间跨 1 时证据不稳定'],
        'method': '人口天数校正的门诊记录 O/E + 对数正态近似区间',
        'window': '用户选择的 14/30/60/90 天病例窗口',
        'missing': '没有匹配记录时 O/E、区间、平滑值和历史负担均不可计算，综合风险降级为天气与 SVI。',
        'limitations': ['未按年龄或性别分层标准化', '不能解释为新发病人数', '小社区波动大', '依赖社区字段匹配质量'],
        'source_file': 'services/community_risk_service.py',
    },
    'smoothed_sir': {
        'anchor': 'smoothed-sir',
        'title': '经验贝叶斯平滑 O/E（兼容字段 smoothed_sir）',
        'summary': '把小样本社区的 O/E 向全体 O/E 拉回，减少一次偶然记录造成的极端值。',
        'formula': 'SmoothedOE = w×OE + (1−w)×GlobalOE；w = Expected/(Expected+8)',
        'variables': ['期望病例越多，w 越接近 1，保留更多社区自身信息'],
        'thresholds': ['用于历史病例负担排序'],
        'method': '经验贝叶斯收缩',
        'window': '与门诊记录 O/E 相同',
        'missing': 'O/E 不可计算时不输出平滑值。',
        'limitations': ['先验强度 8 为当前可审计规则参数'],
        'source_file': 'services/community_risk_service.py',
    },
    'rr_probability': {
        'anchor': 'rr-probability',
        'title': 'P(O/E > 1)',
        'summary': '估计门诊记录观察/期望比高于粗率基线 1 的近似概率，用于社区可能性分档。',
        'formula': 'Observed>0：由 log(O/E) 与 SE≈1/√Observed 计算正态尾部概率；Observed=0：固定返回 0.05',
        'variables': ['观察记录越多，概率估计通常越稳定', '0.05 是当前零观察记录启发式下限，不是从样本估计出的精确概率'],
        'thresholds': ['0–100%，越高表示更可能高于基线'],
        'method': '对数 O/E 正态近似',
        'window': '与门诊记录 O/E 相同',
        'missing': '整个分析窗口没有匹配记录或 O/E 不可计算时不输出概率；窗口有匹配记录且某社区 Observed=0 时显示 0.05。',
        'limitations': ['近似概率', '零观察分支为固定规则', '不等于某位居民患病概率'],
        'source_file': 'services/community_risk_service.py',
    },
    'uncertainty_index': {
        'anchor': 'uncertainty-index',
        'title': '不确定性指数（0–100）',
        'summary': '把 O/E 置信区间宽度和期望记录量合成，数值越高表示证据越不稳定。',
        'formula': 'Uncertainty = min(100, 30×CI宽度 + 样本惩罚)',
        'variables': ['期望病例 <3 加 20 分', '3–7.9 加 8 分', '≥8 不加'],
        'thresholds': ['≥70 时社区综合风险乘 0.93 的不确定性折减'],
        'method': '置信区间宽度启发式指数',
        'window': '与门诊记录 O/E 相同',
        'missing': '有匹配记录但无法计算 CI 时宽度按 3；完全无匹配记录时整个指标为 null。',
        'limitations': ['用于提示谨慎解读', '不是真实误差概率'],
        'source_file': 'services/community_risk_service.py',
    },
    'gistar': {
        'anchor': 'gistar',
        'title': 'Gi* 热点显著性',
        'summary': '判断高风险社区是否在空间上聚集。热点表示周边也偏高。',
        'formula': 'z = (邻域加权风险和 − 全局均值×权重和) / 理论标准差',
        'variables': ['邻域半径 = 最近邻距离中位数×1.6，并限制在 300–5000 米', '半径内权重为 1，孤立点至少连接最近邻', 'p 值由 z 分数近似计算'],
        'thresholds': ['|z|≥1.96 为 95%', '|z|≥2.58 为 99%'],
        'method': 'Getis-Ord Gi* 近似',
        'window': '本次社区风险横截面',
        'missing': '历史分量不可用时标记数据不足；有效社区少于 3 个时标记样本不足。',
        'limitations': ['点位和邻域选择会影响结果', '代理坐标不能用于精细空间推断'],
        'source_file': 'services/community_risk_service.py',
    },
    'expected_excess': {
        'anchor': 'expected-excess',
        'title': '预计额外就诊',
        'summary': '估计相对基线由天气增加的社区门诊量。',
        'formula': 'ExcessVisits = max(RR−1, 0) × VI × BaselineVisits',
        'variables': ['BaselineVisits = clip(社区人口×0.03, 1, 20)'],
        'thresholds': ['只累计正向超额；RR≤1 时记 0'],
        'method': '天气 RR 驱动的增量估计',
        'window': '目标日期',
        'missing': '人口缺失时按 100 人估计，再应用上下限。',
        'limitations': ['用于行动资源排序', '不是精确门诊量预测'],
        'source_file': 'services/community_risk_service.py',
    },
    'data_coverage': {
        'anchor': 'data-coverage',
        'title': '病例数据覆盖率',
        'summary': '分析窗口中成功匹配到已知社区的病例记录占比。',
        'formula': 'Coverage = MatchedRecords / TotalRecords',
        'variables': ['社区名为空或不在当前社区表中会记为未匹配'],
        'thresholds': ['覆盖率越低，社区比较越需要谨慎'],
        'method': '病例社区字段匹配',
        'window': '用户选择的历史病例窗口',
        'missing': '没有记录时显示不可计算。',
        'limitations': ['只衡量社区字段匹配，不衡量诊断编码质量'],
        'source_file': 'services/community_risk_service.py',
    },
    'gis_native_grid': {
        'anchor': 'gis-native-grid',
        'title': '原生 MODIS 网格与县域纳入规则',
        'summary': '以 MYD11A1 h28v06 原生正弦投影像元为分析单位，保留中心点严格落入都昌县研究边界的完整网格。',
        'formula': 'Include(cell) = 1{Center(cell) ∈ Duchang research boundary}',
        'variables': [
            '原生像元边长约 926.625 m，地图显示完整像元多边形',
            '经纬度由 MODIS 正弦投影在球半径 6,371,007.181 m 下转换为 WGS84',
        ],
        'thresholds': ['中心点严格位于研究边界内才纳入', '共纳入 2,593 个县域中心网格'],
        'method': '中心点纳入法与完整原生网格展示',
        'window': '静态空间框架；研究边界为 geoBoundaries ADM3 开放研究边界',
        'missing': '边界外网格不进入公开集合；县界边缘像元仍显示完整几何。',
        'limitations': ['边缘网格可跨越研究边界', '开放研究边界不能替代法定行政边界', '1 km 为产品名义尺度，实际原生像元边长约 926.6 m'],
        'source_file': 'docs/gis/heat-exposure-gis-method.md; services/heat_exposure_gis_service.py',
    },
    'gis_age65_share': {
        'anchor': 'gis-age65-share',
        'title': '65 岁及以上人口比例',
        'summary': 'ASPECT 2020 年龄结构人口栅格聚合到原生 MODIS 网格后，65 岁及以上模型化人口占模型化总人口的比例。',
        'formula': 'Share65 = 100 × ΣP65 / ΣPtotal',
        'variables': [
            'P65 = MODIS 网格内 ASPECT 100 m 像元的 65 岁及以上模型化人口',
            'Ptotal = 同一网格内 ASPECT 100 m 像元的模型化总人口',
        ],
        'thresholds': ['仅在 ΣPtotal > 0 时显示', '地图六分位色阶只服务空间比较，不是医学阈值'],
        'method': 'ASPECT 2020 随机森林人口空间分配结果的网格聚合',
        'window': '人口基准年 2020；空间单位为都昌县研究边界内的原生 MODIS 中心网格',
        'missing': '模型化总人口为 0 的 872 个网格显示无数据；公开产物不输出绝对人口计数。',
        'limitations': ['属于模型化空间分布', '受人口基准年和协变量精度影响', '不能定位个人、家庭或具体住址'],
        'source_file': 'docs/gis/heat-exposure-gis-method.md; services/heat_exposure_gis_service.py',
    },
    'gis_lst_mean': {
        'anchor': 'gis-lst-mean',
        'title': 'Aqua 白天晴空地表温度均值',
        'summary': 'Aqua MYD11A1.061 在 Q3 质量口径下的白天晴空地表温度多年夏季均值。',
        'formula': 'LST_C = Raw×0.02−273.15；Mean = ΣLST_C / n_Q3',
        'variables': [
            'Raw = MYD11A1 LST_Day_1km 有效原始编码',
            'n_Q3 = mandatory QA 位为 00 或 01 且原始编码有效的网格日数',
        ],
        'thresholds': ['地图六分位色阶来自全县有效网格分布，只用于相对空间比较'],
        'method': 'NASA Aqua MYD11A1.061 原生 1 km 像元逐日质量筛选后求均值',
        'window': '2020 至 2024 年，每年 6 月 1 日至 8 月 31 日；本地冻结 448 个场景',
        'missing': '云遮、质量筛选或缺失场景会减少 n_Q3；没有 Q3 合格观测时显示无数据。',
        'limitations': ['晴空采样存在天气选择效应', '地表温度不能替代 2 米气温、室内温度或体感温度', '多年均值会平滑短期极端事件'],
        'source_file': 'docs/gis/heat-exposure-gis-method.md; services/heat_exposure_gis_service.py',
    },
    'gis_q3_coverage': {
        'anchor': 'gis-q3-coverage',
        'title': 'Q3 合格观测覆盖率',
        'summary': '衡量每个网格在 448 个本地冻结场景中有多少天通过 Q3 质量筛选，用于识别云遮和数据稀疏。',
        'formula': 'CoverageQ3 = 100 × n_Q3 / 448',
        'variables': ['n_Q3 = 当前网格 Q3 合格观测天数', '448 = 研究期本地冻结且可复核的 MYD11A1 场景数'],
        'thresholds': ['覆盖率越高代表可用于均值的天数越多', '该指标不衡量温度高低或健康危险程度'],
        'method': '逐网格质量控制计数',
        'window': '2020 至 2024 年夏季本地冻结场景',
        'missing': '分母固定为 448；质量不合格、云遮和场景缺失均不会进入分子。',
        'limitations': ['只能描述有效观测数量', '不能校正晴空采样偏差', '空间差异可能由云量和质量标志共同造成'],
        'source_file': 'docs/gis/heat-exposure-gis-method.md; services/heat_exposure_gis_service.py',
    },
    'gis_tree_cover': {
        'anchor': 'gis-tree-cover',
        'title': '树木覆盖比例',
        'summary': 'ESA WorldCover 2020 v100 中类别 10 的源像元覆盖权重，聚合到原生 MODIS 网格。',
        'formula': 'TreeCover = 100 × Σw(class=10) / Σw(valid)',
        'variables': ['w = WorldCover 源像元与目标 MODIS 网格相交时使用的覆盖权重', 'class=10 = Tree cover'],
        'thresholds': ['地图六分位色阶只服务空间比较'],
        'method': '10 m 分类栅格按源像元覆盖权重聚合',
        'window': 'ESA WorldCover 2020 v100',
        'missing': '目标网格没有有效 WorldCover 支持时显示无数据。',
        'limitations': ['全球产品存在分类误差', '2020 快照不能反映后续土地覆盖变化', '比例不描述树冠高度或遮阴可达性'],
        'source_file': 'docs/gis/heat-exposure-gis-method.md; services/heat_exposure_gis_service.py',
    },
    'gis_built_up': {
        'anchor': 'gis-built-up',
        'title': '建成区覆盖比例',
        'summary': 'ESA WorldCover 2020 v100 中类别 50 的源像元覆盖权重，聚合到原生 MODIS 网格。',
        'formula': 'BuiltUp = 100 × Σw(class=50) / Σw(valid)',
        'variables': ['w = WorldCover 源像元与目标 MODIS 网格相交时使用的覆盖权重', 'class=50 = Built-up'],
        'thresholds': ['地图六分位色阶只服务空间比较'],
        'method': '10 m 分类栅格按源像元覆盖权重聚合',
        'window': 'ESA WorldCover 2020 v100',
        'missing': '目标网格没有有效 WorldCover 支持时显示无数据。',
        'limitations': ['全球产品存在分类误差', '比例不描述建筑密度、高度、材料或室内热环境', '2020 快照不能反映后续建设变化'],
        'source_file': 'docs/gis/heat-exposure-gis-method.md; services/heat_exposure_gis_service.py',
    },
    'gis_permanent_water': {
        'anchor': 'gis-permanent-water',
        'title': '近似永久水域比例',
        'summary': 'ESA WorldCover 2020 v100 中类别 80 的源像元覆盖权重，用于描述网格内近似永久水体背景。',
        'formula': 'PermanentWater = 100 × Σw(class=80) / Σw(valid)',
        'variables': ['w = WorldCover 源像元覆盖权重', 'class=80 = Permanent water bodies'],
        'thresholds': ['地图六分位色阶只服务空间比较'],
        'method': '10 m 分类栅格按源像元覆盖权重聚合',
        'window': 'ESA WorldCover 2020 v100',
        'missing': '目标网格没有有效 WorldCover 支持时显示无数据。',
        'limitations': ['属于近似覆盖比例', '未进行严格大地测量面积计算', '季节性水体和岸线分类误差会影响结果'],
        'source_file': 'docs/gis/heat-exposure-gis-method.md; services/heat_exposure_gis_service.py',
    },
    'gis_mean_elevation': {
        'anchor': 'gis-mean-elevation',
        'title': '平均表面高程',
        'summary': 'Copernicus DEM GLO-30 数字表面模型按有效源像元权重聚合到原生 MODIS 网格。',
        'formula': 'MeanElevation = Σ(Elevation×w_valid) / Σw_valid',
        'variables': ['Elevation = GLO-30 源像元表面高程', 'w_valid = 有效源像元覆盖权重'],
        'thresholds': ['地图六分位色阶只服务空间比较'],
        'method': '约 30 m 数字表面模型覆盖权重平均',
        'window': 'Copernicus DEM GLO-30 产品版本对应的静态表面',
        'missing': '目标网格没有有效 DEM 支持时显示无数据。',
        'limitations': ['数字表面模型包含植被和建筑等地物高度', '不能直接解释裸地地形', '空间聚合会平滑局地起伏'],
        'source_file': 'docs/gis/heat-exposure-gis-method.md; services/heat_exposure_gis_service.py',
    },
    'gis_validation': {
        'anchor': 'gis-validation',
        'title': '冻结产物独立复核门槛',
        'summary': '发布器只接收通过失败关闭复核的冻结输入，并在 GeoJSON 中保留输入 SHA-256 指纹和质量摘要。',
        'formula': 'Publish = 1{validation_pass = true ∧ status = pass ∧ hard_failures = 0}',
        'variables': [
            '复核范围包含网格全集、日历与本地场景、资产完整性和抽样面板重算',
            'SHA-256 指纹用于确认发布输入与冻结证据一致',
        ],
        'thresholds': ['任何硬失败都会停止 GeoJSON 构建', '当前冻结报告硬失败数为 0'],
        'method': '独立复核程序与发布前失败关闭校验',
        'window': '本次 2020 至 2024 年夏季冻结数据版本',
        'missing': '验证报告缺失、状态不通过、网格 ID 不一致或边界要素异常时停止构建。',
        'limitations': ['程序复核用于检查可重复性与内部一致性', '不代表外部机构认证', '上游数据集自身误差仍会传递到结果'],
        'source_file': 'docs/gis/heat-exposure-gis-method.md; services/heat_exposure_gis_service.py',
    },
    'mae': {
        'anchor': 'mae',
        'title': 'MAE（平均绝对误差）',
        'summary': '预测门诊量与实际门诊量之间绝对差值的平均数。越低越好。',
        'formula': 'MAE = mean(|Actual − Predicted|)',
        'variables': ['单位与门诊量相同'],
        'thresholds': ['应结合实际日门诊量规模判断'],
        'method': '离线回测指标',
        'window': '回测报告覆盖期',
        'missing': '没有回测报告时不展示数值。',
        'limitations': ['不反映误差方向', '不能单独证明预警校准良好'],
        'source_file': 'scripts/backtest_forecast.py',
    },
    'rmse': {
        'anchor': 'rmse',
        'title': 'RMSE（均方根误差）',
        'summary': '对较大的预测错误惩罚更重。越低越好。',
        'formula': 'RMSE = sqrt(mean((Actual − Predicted)²))',
        'variables': ['单位与门诊量相同'],
        'thresholds': ['与 MAE 一起看；RMSE 明显更高常表示存在少数大误差'],
        'method': '离线回测指标',
        'window': '回测报告覆盖期',
        'missing': '没有回测报告时不展示数值。',
        'limitations': ['容易被少数极端日影响'],
        'source_file': 'scripts/backtest_forecast.py',
    },
    'interval_coverage': {
        'anchor': 'interval-coverage',
        'title': '预测区间覆盖率',
        'summary': '实际门诊量落在预测下界和上界之间的天数比例。',
        'formula': 'Coverage = 区间包含实际值的有效天数 / 同时具有实际值、下界和上界的回测天数',
        'variables': ['应同时观察区间宽度，过宽也会得到高覆盖率'],
        'thresholds': ['目标应接近区间名义置信水平'],
        'method': '离线回测区间指标',
        'window': '回测报告覆盖期',
        'missing': '缺少实际值或上下界的日期会从分子、分母同时排除；没有有效日期时不展示。',
        'limitations': ['高覆盖率不一定代表区间有用'],
        'source_file': 'scripts/backtest_forecast.py',
    },
}


def get_metric_explanations():
    """返回模板使用的指标解释目录。"""
    return METRIC_EXPLANATIONS


def get_metric_explanation_groups():
    """返回透明度页使用的分组。"""
    return METRIC_EXPLANATION_GROUPS
