# -*- coding: utf-8 -*-
"""Compatibility layer for legacy imports."""

from services.user import (
    caregiver_action_log,
    caregiver_dashboard,
    caregiver_pair_create,
    caregiver_pair_detail,
    caregiver_relay_backup,
    caregiver_relay_escalate,
    caregiver_wechat_template,
    community_announce,
    community_dashboard,
    community_detail,
    community_risk,
    community_wechat,
    elder_dashboard,
    health_assessment,
    pair_backup_contact,
    pair_escalate,
    pair_management,
    profile,
    update_location,
    user_dashboard,
)

__all__ = [
    'user_dashboard',
    'elder_dashboard',
    'pair_management',
    'caregiver_dashboard',
    'caregiver_pair_create',
    'caregiver_pair_detail',
    'caregiver_action_log',
    'caregiver_wechat_template',
    'pair_escalate',
    'pair_backup_contact',
    'caregiver_relay_escalate',
    'caregiver_relay_backup',
    'community_dashboard',
    'community_detail',
    'community_wechat',
    'community_announce',
    'community_risk',
    'health_assessment',
    'profile',
    'update_location',
]
